// src/components/common/FontLoader/FontLoader.tsx
import React from 'react';
import { AsyncFont } from '../AsyncFont/AsyncFont';

// Font loader component
export const FontLoader: React.FC = () => {
  return (
    <>
      {/* Inter Fonts */}
      <AsyncFont
        src={require('@/assets/fonts/Inter/Inter-Light.ttf')}
        fontFamily='Inter-Light'
      />
      <AsyncFont
        src={require('@/assets/fonts/Inter/Inter-LightItalic.ttf')}
        fontFamily='Inter-LightItalic'
      />
      <AsyncFont
        src={require('@/assets/fonts/Inter/Inter-Regular.ttf')}
        fontFamily='Inter-Regular'
      />
      <AsyncFont
        src={require('@/assets/fonts/Inter/Inter-Italic.ttf')}
        fontFamily='Inter-Italic'
      />
      <AsyncFont
        src={require('@/assets/fonts/Inter/Inter-Medium.ttf')}
        fontFamily='Inter-Medium'
      />
      <AsyncFont
        src={require('@/assets/fonts/Inter/Inter-MediumItalic.ttf')}
        fontFamily='Inter-MediumItalic'
      />
      <AsyncFont
        src={require('@/assets/fonts/Inter/Inter-SemiBold.ttf')}
        fontFamily='Inter-SemiBold'
      />
      <AsyncFont
        src={require('@/assets/fonts/Inter/Inter-SemiBoldItalic.ttf')}
        fontFamily='Inter-SemiBoldItalic'
      />
      <AsyncFont
        src={require('@/assets/fonts/Inter/Inter-Bold.ttf')}
        fontFamily='Inter-Bold'
      />
      <AsyncFont
        src={require('@/assets/fonts/Inter/Inter-BoldItalic.ttf')}
        fontFamily='Inter-BoldItalic'
      />
      <AsyncFont
        src={require('@/assets/fonts/Inter/Inter-ExtraBold.ttf')}
        fontFamily='Inter-ExtraBold'
      />
      <AsyncFont
        src={require('@/assets/fonts/Inter/Inter-ExtraBoldItalic.ttf')}
        fontFamily='Inter-ExtraBoldItalic'
      />
      {/* Roboto Fonts */}
      <AsyncFont
        src={require('@/assets/fonts/Roboto/Roboto-Light.ttf')}
        fontFamily='Roboto-Light'
      />
      <AsyncFont
        src={require('@/assets/fonts/Roboto/Roboto-LightItalic.ttf')}
        fontFamily='Roboto-LightItalic'
      />
      <AsyncFont
        src={require('@/assets/fonts/Roboto/Roboto-Regular.ttf')}
        fontFamily='Roboto-Regular'
      />
      <AsyncFont
        src={require('@/assets/fonts/Roboto/Roboto-Italic.ttf')}
        fontFamily='Roboto-Italic'
      />
      <AsyncFont
        src={require('@/assets/fonts/Roboto/Roboto-Medium.ttf')}
        fontFamily='Roboto-Medium'
      />
      <AsyncFont
        src={require('@/assets/fonts/Roboto/Roboto-MediumItalic.ttf')}
        fontFamily='Roboto-MediumItalic'
      />
      <AsyncFont
        src={require('@/assets/fonts/Roboto/Roboto-SemiBold.ttf')}
        fontFamily='Roboto-SemiBold'
      />
      <AsyncFont
        src={require('@/assets/fonts/Roboto/Roboto-SemiBoldItalic.ttf')}
        fontFamily='Roboto-SemiBoldItalic'
      />
      <AsyncFont
        src={require('@/assets/fonts/Roboto/Roboto-Bold.ttf')}
        fontFamily='Roboto-Bold'
      />
      <AsyncFont
        src={require('@/assets/fonts/Roboto/Roboto-BoldItalic.ttf')}
        fontFamily='Roboto-BoldItalic'
      />
      {/* Poppins Fonts */}
      <AsyncFont
        src={require('@/assets/fonts/Poppins/Poppins-Light.ttf')}
        fontFamily='Poppins-Light'
      />
      <AsyncFont
        src={require('@/assets/fonts/Poppins/Poppins-LightItalic.ttf')}
        fontFamily='Poppins-LightItalic'
      />
      <AsyncFont
        src={require('@/assets/fonts/Poppins/Poppins-Regular.ttf')}
        fontFamily='Poppins-Regular'
      />
      <AsyncFont
        src={require('@/assets/fonts/Poppins/Poppins-Italic.ttf')}
        fontFamily='Poppins-Italic'
      />
      <AsyncFont
        src={require('@/assets/fonts/Poppins/Poppins-Medium.ttf')}
        fontFamily='Poppins-Medium'
      />
      <AsyncFont
        src={require('@/assets/fonts/Poppins/Poppins-MediumItalic.ttf')}
        fontFamily='Poppins-MediumItalic'
      />
      <AsyncFont
        src={require('@/assets/fonts/Poppins/Poppins-SemiBold.ttf')}
        fontFamily='Poppins-SemiBold'
      />
      <AsyncFont
        src={require('@/assets/fonts/Poppins/Poppins-SemiBoldItalic.ttf')}
        fontFamily='Poppins-SemiBoldItalic'
      />
      <AsyncFont
        src={require('@/assets/fonts/Poppins/Poppins-Bold.ttf')}
        fontFamily='Poppins-Bold'
      />
      <AsyncFont
        src={require('@/assets/fonts/Poppins/Poppins-BoldItalic.ttf')}
        fontFamily='Poppins-BoldItalic'
      />
      {/* Lato Fonts */}
      <AsyncFont
        src={require('@/assets/fonts/Lato/Lato-Light.ttf')}
        fontFamily='Lato-Light'
      />
      <AsyncFont
        src={require('@/assets/fonts/Lato/Lato-LightItalic.ttf')}
        fontFamily='Lato-LightItalic'
      />
      <AsyncFont
        src={require('@/assets/fonts/Lato/Lato-Regular.ttf')}
        fontFamily='Lato-Regular'
      />
      <AsyncFont
        src={require('@/assets/fonts/Lato/Lato-Italic.ttf')}
        fontFamily='Lato-Italic'
      />
      <AsyncFont
        src={require('@/assets/fonts/Lato/Lato-Medium.ttf')}
        fontFamily='Lato-Medium'
      />
      <AsyncFont
        src={require('@/assets/fonts/Lato/Lato-MediumItalic.ttf')}
        fontFamily='Lato-MediumItalic'
      />
      <AsyncFont
        src={require('@/assets/fonts/Lato/Lato-SemiBold.ttf')}
        fontFamily='Lato-SemiBold'
      />
      <AsyncFont
        src={require('@/assets/fonts/Lato/Lato-SemiBoldItalic.ttf')}
        fontFamily='Lato-SemiBoldItalic'
      />
      <AsyncFont
        src={require('@/assets/fonts/Lato/Lato-Bold.ttf')}
        fontFamily='Lato-Bold'
      />
      <AsyncFont
        src={require('@/assets/fonts/Lato/Lato-BoldItalic.ttf')}
        fontFamily='Lato-BoldItalic'
      />
      {/* Montserrat Fonts */}
      <AsyncFont
        src={require('@/assets/fonts/Montserrat/Montserrat-Light.ttf')}
        fontFamily='Montserrat-Light'
      />
      <AsyncFont
        src={require('@/assets/fonts/Montserrat/Montserrat-LightItalic.ttf')}
        fontFamily='Montserrat-LightItalic'
      />
      <AsyncFont
        src={require('@/assets/fonts/Montserrat/Montserrat-Regular.ttf')}
        fontFamily='Montserrat-Regular'
      />
      <AsyncFont
        src={require('@/assets/fonts/Montserrat/Montserrat-Italic.ttf')}
        fontFamily='Montserrat-Italic'
      />
      <AsyncFont
        src={require('@/assets/fonts/Montserrat/Montserrat-Medium.ttf')}
        fontFamily='Montserrat-Medium'
      />
      <AsyncFont
        src={require('@/assets/fonts/Montserrat/Montserrat-MediumItalic.ttf')}
        fontFamily='Montserrat-MediumItalic'
      />
      <AsyncFont
        src={require('@/assets/fonts/Montserrat/Montserrat-SemiBold.ttf')}
        fontFamily='Montserrat-SemiBold'
      />
      <AsyncFont
        src={require('@/assets/fonts/Montserrat/Montserrat-SemiBoldItalic.ttf')}
        fontFamily='Montserrat-SemiBoldItalic'
      />
      <AsyncFont
        src={require('@/assets/fonts/Montserrat/Montserrat-Bold.ttf')}
        fontFamily='Montserrat-Bold'
      />
      <AsyncFont
        src={require('@/assets/fonts/Montserrat/Montserrat-BoldItalic.ttf')}
        fontFamily='Montserrat-BoldItalic'
      />
    </>
  );
};
