export const ROUTES = {
  ROOT: "/",
  INTRO: "/auth/introduction",
  MAIN_STORY: "/story/main-story",
  SIGN_IN: "/auth/sign-in",
  CREATE_ACCOUNT: "/auth/create-account",
  FORGOT_PASSWORD: "/auth/forgot-password",
  ONBOARDING: "/onboarding",
  PAYMENT: "/payment",
  PAYMENT_DETAIL: "/payment/payment-detail",
  PAYMENT_REFERRAL_CODE: "/payment/referral-code",
  PAYMENT_DELIVERY_ADDRESS: "/payment/delivery-address",
  PAYMENT_CONFIRM_ADDRESS: "/payment/sign-up-confirm-address",
  PAYMENT_INFO: "/payment/payment-info",
  ENABLE_NOTIFICATIONS: "/payment/enable-notifications",
  ADD_MOMENTS: "/story/add-moments",
  SELECT_PHOTOS: "/story/select-photos",
  PRINT_PREVIEW: "/print-preview",
  SIGN_UP: "/payment",
  HISTORY: "/story/history",
  ACCOUNT: "/account",
  PRINT_SETTINGS: "/print-settings",
  REMINDERS: "/reminders",
  REFER_FRIENDS: "/refer-friends",
  GIFT_TIMESHEL: "/payment/gift-timeshel",
  CONTACT_US: "/contact-us",
  TOUR: "/story/tour",
} as const;

export const PROTECTED_ROUTES = [
  "/story",
  "/print-preview",
  "/onboarding",
  "/crop-moment",
  "/payment",
  "/account",
  "/additional-recipients",
  "/print-settings",
  "/reminders",
  "/refer-friends",
  "/contact-us",
] as const;

export const AUTH_ROUTES = [
  ROUTES.SIGN_IN,
  ROUTES.CREATE_ACCOUNT,
  ROUTES.FORGOT_PASSWORD,
  ROUTES.INTRO,
] as const;
