import type { ColorType } from '@/theme';
import { BorderRadius } from '@/theme/borderRadius';
import { FontSize } from '@/theme/fonts';

export default (colors: ColorType) => ({
  typography: {
    default: FontSize.MEDIUM,
    smaller: FontSize.SMALL,
    subtext: FontSize.EXTRA_SMALL,
  },
  roundness: {
    default: BorderRadius.SMALL,
    rounded: BorderRadius.FULL,
  },
  colors: {
    primaryOutline: {
      border: colors.primary,
      borderHighlight: colors.palette.primary[50],
      borderDisabled: colors.palette.primary[60],
      background: colors.background,
      backgroundHighlight: colors.palette.secondary[80],
      backgroundDisabled: colors.background,
      label: colors.primary,
      labelHighlight: colors.primary,
      labelDisabled: colors.primary,
    },
    primary: {
      border: colors.primary,
      borderHighlight: colors.palette.primary[50],
      borderDisabled: colors.palette.primary[60],
      background: colors.primary,
      backgroundHighlight: colors.palette.primary[50],
      backgroundDisabled: colors.palette.primary[60],
      label: colors.white,
      labelHighlight: colors.white,
      labelDisabled: colors.white,
    },
    secondary: {
      border: colors.secondary,
      borderHighlight: colors.palette.secondary[50],
      borderDisabled: colors.palette.secondary[60],
      background: colors.palette.secondary[60],
      backgroundHighlight: colors.palette.secondary[50],
      backgroundDisabled: colors.palette.secondary[60],
      label: colors.black,
      labelHighlight: colors.black,
      labelDisabled: colors.black,
    },
    custom: {
      border: colors.primary,
      borderHighlight: colors.palette.primary[50],
      borderDisabled: colors.palette.primary[60],
      background: colors.primary,
      backgroundHighlight: colors.palette.primary[50],
      backgroundDisabled: colors.palette.primary[60],
      label: colors.white,
      labelHighlight: colors.white,
      labelDisabled: colors.white,
    },
    black: {
      border: colors.pureBlack,
      borderHighlight: colors.black,
      borderDisabled: colors.pureBlack,
      background: colors.pureBlack,
      backgroundHighlight: colors.black,
      backgroundDisabled: colors.pureBlack,
      label: colors.pureWhite,
      labelHighlight: colors.pureWhite,
      labelDisabled: colors.pureWhite,
    },
    white: {
      border: colors.pureWhite,
      borderHighlight: colors.white,
      borderDisabled: colors.pureWhite,
      background: colors.pureWhite,
      backgroundHighlight: colors.white,
      backgroundDisabled: colors.pureWhite,
      label: colors.pureBlack,
      labelHighlight: colors.pureBlack,
      labelDisabled: colors.pureBlack,
    },
    borderRed: {
      border: colors.error,
      borderHighlight: colors.error,
      borderDisabled: colors.error,
      background: colors.palette.transparent,
      backgroundHighlight: colors.palette.transparent,
      backgroundDisabled: colors.palette.transparent,
      label: colors.error,
      labelHighlight: colors.error,
      labelDisabled: colors.error,
    },
    red: {
      border: colors.error,
      borderHighlight: colors.error,
      borderDisabled: colors.error,
      background: colors.error,
      backgroundHighlight: colors.error,
      backgroundDisabled: colors.error,
      label: colors.white,
      labelHighlight: colors.white,
      labelDisabled: colors.white,
    },
    tertiary: {
      border: colors.primary,
      borderHighlight: colors.primary,
      borderDisabled: colors.primary,
      background: colors.palette.secondary[60],
      backgroundHighlight: colors.palette.secondary[50],
      backgroundDisabled: colors.palette.secondary[60],
      label: colors.primary,
      labelHighlight: colors.black,
      labelDisabled: colors.palette.grey[50],
    },
  },
  animationConfig: { duration: 200 },
  minElevationLevel: 0,
  maxElevationLevel: 4,
});
